include:
  - project: 'devops/gitlab-ci-template'
    file: '/.Docker.gitlab-ci.yml'

build-docker:
  extends: .build-docker-template
  variables:
    _DOCKER_FILE_PATH: images/production/Containerfile
    _DOCKER_CONTEXT_PATH: .
    _DOCKER_BUILD_EXTRA_ARGS: >-
      --build-arg FRAPPE_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg FRAPPE_PATH=https://oauth2:$CI_GITLAB_ACCESS_TOKEN@gitlab.yody.io/erp/next/frappe.git
      --build-arg ERPNEXT_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg ERPNEXT_REPO=https://oauth2:$CI_GITLAB_ACCESS_TOKEN@gitlab.yody.io/erp/next/erpnext.git
  before_script:
    - _DOCKER_RELEASE_IMAGE_TAG="$CI_COMMIT_REF_NAME-`printf %010d $CI_PIPELINE_ID`-$CI_COMMIT_SHORT_SHA"
    - echo "_DOCKER_BUILD_EXTRA_ARGS=$_DOCKER_BUILD_EXTRA_ARGS"
    - echo "docker build --cache-from $CI_REGISTRY_IMAGE:$_DOCKER_CACHE_IMAGE_TAG --tag $CI_REGISTRY_IMAGE:$_DOCKER_RELEASE_IMAGE_TAG --tag $CI_REGISTRY_IMAGE:$_DOCKER_CACHE_IMAGE_TAG -f $_DOCKER_FILE_PATH $_DOCKER_BUILD_EXTRA_ARGS $_DOCKER_CONTEXT_PATH"