include:
  - project: 'nentangso/devops/gitlab-ci-template'
    file: '/.Docker.gitlab-ci.yml'
  - project: 'nentangso/devops/gitlab-ci-template'
    file: 'Trigger.ArgoCD.gitlab-ci.yml'

.continuous-integration-overrides:
  rules:
  - if: $CI_PIPELINE_SOURCE =~ /^(merge_request_event|external_pull_request_event)$/
    when: never
  - if: $CI_COMMIT_REF_NAME =~ /^(develop|main)$/
  - when: never

build-docker:
  extends: .build-docker-template
  variables:
    _DOCKER_FILE_PATH: images/production/Containerfile
    _DOCKER_CONTEXT_PATH: .
    _DOCKER_BUILD_EXTRA_ARGS: >-
      --no-cache
      --build-arg FRAPPE_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg FRAPPE_PATH=https://$CI_GITLAB_USER:$CI_GITLAB_ACCESS_TOKEN@gitlab.com/nentangso/west/development/frappe/frappe.git
      --build-arg ERPNEXT_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg ERPNEXT_REPO=https://$CI_GITLAB_USER:$CI_GITLAB_ACCESS_TOKEN@gitlab.com/nentangso/west/development/frappe/erpnext.git
      --build-arg HRMS_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg HRMS_REPO=https://$CI_GITLAB_USER:$CI_GITLAB_ACCESS_TOKEN@gitlab.com/nentangso/west/development/frappe/hrms.git
      --build-arg CUSTOM_APP1_NAME=gowest_erp
      --build-arg CUSTOM_APP1_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg CUSTOM_APP1_REPO=https://$CI_GITLAB_USER:$CI_GITLAB_ACCESS_TOKEN@gitlab.com/nentangso/west/development/golfy/gowest_erp.git
      --build-arg CUSTOM_APP2_NAME=golfy
      --build-arg CUSTOM_APP2_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg CUSTOM_APP2_REPO=https://$CI_GITLAB_USER:$CI_GITLAB_ACCESS_TOKEN@gitlab.com/nentangso/west/development/golfy/golfy.git
      --build-arg CUSTOM_APP3_NAME=gowest
      --build-arg CUSTOM_APP3_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg CUSTOM_APP3_REPO=https://$CI_GITLAB_USER:$CI_GITLAB_ACCESS_TOKEN@gitlab.com/nentangso/west/development/subscription/gowest.git
