include:
  - project: 'nentangso/devops/gitlab-ci-template'
    file: '/.Docker.gitlab-ci.yml'
  - project: 'nentangso/devops/gitlab-ci-template'
    file: 'Trigger.ArgoCD.gitlab-ci.yml'

build-docker:
  extends: .build-docker-template
  variables:
    _DOCKER_FILE_PATH: images/production/Containerfile
    _DOCKER_CONTEXT_PATH: .
    _DOCKER_BUILD_EXTRA_ARGS: >-
      --no-cache
      --build-arg FRAPPE_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg FRAPPE_PATH=https://${CI_GITLAB_USER:-oauth2}:$CI_GITLAB_ACCESS_TOKEN@gitlab.yody.io/erp/next/frappe.git
      --build-arg ERPNEXT_BRANCH=$CI_COMMIT_REF_NAME
      --build-arg ERPNEXT_REPO=https://${CI_GITLAB_USER:-oauth2}:$CI_GITLAB_ACCESS_TOKEN@gitlab.yody.io/erp/next/erpnext.git
