name: Stable build by Go West Tech

on:
  # Triggered from go-west-tech-jsc/frappe, go-west-tech-jsc/erpnext and go-west-tech-jsc/hrms on releases
  repository_dispatch:

  workflow_dispatch:

jobs:
  v15:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      repo: erpnext
      version: "15"
      push: false
      python_version: 3.11.6
      node_version: 18.18.2