name: Stable build by Go West Tech

on:
  # Triggered from go-west-tech-jsc/frappe, go-west-tech-jsc/erpnext and go-west-tech-jsc/hrms on releases
  repository_dispatch:

  workflow_dispatch:

jobs:
  v15:
    uses: ./.github/workflows/docker-build-push_by_go_west_tech.yml
    with:
      repo: erpnext
      version: "15"
      push: ${{ github.repository == 'go-west-tech-jsc/frappe_docker' && github.event_name != 'pull_request' }}
      python_version: 3.11.6
      node_version: 18.18.2
